apiVersion: v1                                  # Specifies the Kubernetes API version.
kind: Secret                                    # Defines the type of Kubernetes resource in this it is Secret
metadata:                                       
  name: mongodb-secret                            # Sets the name of the Secret resource.
immutable: false                                     # Indicates whether the Secret is mutable
type: Opaque                                        # Specifies the type of data stored in the Secret.
data:
  password: cGFzc3dvcmQxMjM=                        # Stores an encoded password for MongoDB authentication.