apiVersion: v1                                               # Specifies the Kubernetes API version for PersistentVolumeClaim.
kind: PersistentVolumeClaim                                   # Defines the type of Kubernetes resource i.e. PersistentVolumeClaim.
metadata:                                                     
  name: mongo-pvc                                            # Sets the name of the PersistentVolumeClaim resource.
spec:
  accessModes:                                                  # Specifies the access mode for the volume claim.
    - ReadWriteMany                                               # Allows multiple nodes to read and write to the volume.
  resources:                                                       # Specifies the resources requested by the volume claim.
    requests:
      storage: 1Gi                                                  # Requests 1 gigabyte of storage for the volume claim.
  storageClassName: "demo-storage"                                     # Specifies the storage class for the volume claim.